### ISSUE TITLE
Add YouTubeRebornPlus + Make repo SideStore compatible

### ISSUE THREAD

**Issue by Macleykun** [arichornlover/arichornlover.github.io#1]
Hello!

Thank you for making YouTubeRebornPlus! Is it possible to add the latest ipa to this repo so i can update easily from SideStore?

https://github.com/arichorn/YouTubeRebornPlus

Thank you in advance!

**Comment by arichornlover** [comment]
Sure. That’s gonna be the 3rd YT tweak in that repo but alright.

**Comment by Macleykun** [comment]
Thanks! I really appreciate it!
________________________________
Van: arichorn ***@***.***>
Verzonden: Friday, June 9, 2023 9:29:59 PM
Aan: arichorn/arichorn.github.io ***@***.***>
CC: Macley ***@***.***>; Author ***@***.***>
Onderwerp: Re: [arichorn/arichorn.github.io] Add YouTubeRebornPlus (Issue #1)


Sure. That’s gonna be the 3rd YT tweak in that repo but alright.

**Comment by arichornlover** [comment]
It’s added! + updated app icons!

**Comment by Macleykun** [comment]
Thanks!
I did try it out just now, but is it a client-side issue if the error:
“YouTube” could not be installed. The bundle ID “com.google.ios.youtube” does not match the one specified by the source (“com.google.ios.youtubereborn”).
I also noticed the icon is white for some reason
![IMG_3468](https://github.com/arichorn/arichorn.github.io/assets/26381427/4670801a-2657-40a1-939b-9f77444adb38)

**Comment by arichornlover** [comment]
That was my mistake 😅
And I fixed the white icon issue aswell.

**Comment by arichornlover** [comment]
Also that’s YouTube Reborn not YouTubeRebornPlus btw

**Comment by Macleykun** [comment]
> That was my mistake 😅 And I fixed the white icon issue aswell.

thanks! i did try it out again (saw the icon update) but for somereason it still throws the same error.
I tried the direct url to the apps.json file but the same error re-appeard weirdly enough. I think it might be a caching issue on my end (if it works on your end).



> Also that’s YouTube Reborn not YouTubeRebornPlus btw

ooh i see! Would it be possible to ~also~ upload the Plus version? As it has more features and whatnot?

Also, i believe the current apps.JSON isn’t working well with SideStore as it doesn’t have the correct format.
![IMG_3469](https://github.com/arichorn/arichorn.github.io/assets/26381427/17fb3b6f-b4f7-45ee-9908-752a4e81faa4)

**Comment by Macleykun** [comment]
Also, completely unrelevant. But if you want a higher res of your current pfp: https://i.redd.it/sqqsko3hmn571.jpg <Warning NSFW
Idk, somehow it bothered me that it was so low res :P

**Comment by arichornlover** [comment]
> thanks! i did try it out again (saw the icon update) but for somereason it still throws the same error. I tried the direct url to the apps.json file but the same error re-appeard weirdly enough. I think it might be a caching issue on my end (if it works on your end).
ooh i see! Would it be possible to ~also~ upload the Plus version? As it has more features and whatnot?

I might have to make a new apps.json for sidestore and then see if it works.

**Comment by Macleykun** [comment]
sure thing! Sorry to hear you have to make another apps.json just for this.

**Comment by Macleykun** [comment]
Heya, is it possible to look at this issue maybe so that all 3 apps work from your SideStore source? https://github.com/arichorn/arichorn.github.io/pull/3#issuecomment-1625605966

**Comment by arichornlover** [comment]
Well there is a way to do it. I can change the bundle ids in the ipas and then it can change them. And then anyone will be able to download any of them which is the best bet

**Comment by Macleykun** [comment]
Sounds like a good plan!! 

>

**Comment by Macleykun** [comment]
> Well there is a way to do it. I can change the bundle ids in the ipas and then it can change them. And then anyone will be able to download any of them which is the best bet

Heya, I saw ya updated the apps2.json but the bundle id sadly still conflicts. Could you have a look perhaps this weekend/sometime :)?

**Comment by arichornlover** [comment]
I’m gonna make a alternative release of YouTubeRebornPlus give me a moment

**Comment by arichornlover** [comment]
> > Well there is a way to do it. I can change the bundle ids in the ipas and then it can change them. And then anyone will be able to download any of them which is the best bet
> 
> Heya, I saw ya updated the apps2.json but the bundle id sadly still conflicts. Could you have a look perhaps this weekend/sometime :)?

That wasn’t the Bundle ID, the conflicts was because of me forgetting to change the Version Number and also Apps2.json had an update. Theres a tweak that uses a completely different bundle id

**Comment by Macleykun** [comment]
Hmm I see
Say, I know this is off-topic but which version of YouTube is the best actually? Because the latest update of YouTube reborn seemed to not have isponsorsblock.
Maybe it’s and idea to have a list which version contains what?

**Comment by arichornlover** [comment]
> Hmm I see Say, I know this is off-topic but which version of YouTube is the best actually? Because the latest update of YouTube reborn seemed to not have isponsorsblock. Maybe it’s and idea to have a list which version contains what?

I got rid of the SponsorBlock stuff inside the YouTube Reborn button because it never worked in there. and also iSponsorBlock wasn’t included but I could include it.

**Comment by Macleykun** [comment]
Hmm, then I think I downloaded the wrong version, n9 worries :)
I’ll close the issue then as I did download through SideStore! Thank you so much :) !
________________________________
Van: arichorn ***@***.***>
Verzonden: Tuesday, August 1, 2023 12:04:15 AM
Aan: arichorn/arichorn.github.io ***@***.***>
CC: Macley ***@***.***>; Author ***@***.***>
Onderwerp: Re: [arichorn/arichorn.github.io] Add YouTubeRebornPlus + Make repo SideStore compatible (Issue #1)


Hmm I see Say, I know this is off-topic but which version of YouTube is the best actually? Because the latest update of YouTube reborn seemed to not have isponsorsblock. Maybe it’s and idea to have a list which version contains what?

I got rid of the SponsorBlock stuff inside the YouTube Reborn button because it never worked in there. and also iSponsorBlock wasn’t included but I could include it.
